use indexmap::IndexMap;

use crate::generate::Rule;
use crate::theme::{Group, ResolvedTheme};

pub struct EmitOptions {
    pub minify: bool,
    pub source_comments: bool,
    pub dedup: bool,
    pub base: String,
    pub version: String,
}

const MINIMAL_RESET: &str = "*,::before,::after{box-sizing:border-box}\
* {margin:0}\
body{line-height:1.5;-webkit-font-smoothing:antialiased}\
img,picture,video,canvas,svg{display:block;max-width:100%}\
input,button,textarea,select{font:inherit}";

fn min_width_order(value: &str) -> f64 {
    let num: String = value.chars().take_while(|c| c.is_ascii_digit() || *c == '.').collect();
    num.parse().unwrap_or(f64::MAX)
}

pub fn emit_css(rules: &[Rule], opts: &EmitOptions) -> String {
    let nl = if opts.minify { "" } else { "\n" };
    let mut out = String::new();

    if !opts.minify {
        out.push_str(&format!("/* Generated by PresetCSS v{} - do not edit by hand */\n\n", opts.version));
    }

    match opts.base.as_str() {
        "none" => {}
        "minimal" => {
            out.push_str(MINIMAL_RESET);
            out.push_str(nl);
            if !opts.minify {
                out.push('\n');
            }
        }
        other => {
            out.push_str(other);
            out.push_str(nl);
        }
    }

    let mut root: Vec<&Rule> = Vec::new();
    let mut media: IndexMap<String, Vec<&Rule>> = IndexMap::new();
    for r in rules {
        match &r.media {
            None => root.push(r),
            Some(m) => media.entry(m.clone()).or_default().push(r),
        }
    }

    write_block(&mut out, &root, opts, 0);

    let mut keys: Vec<String> = media.keys().cloned().collect();
    keys.sort_by(|a, b| min_width_order(a).partial_cmp(&min_width_order(b)).unwrap());
    for key in keys {
        let bucket = &media[&key];
        out.push_str(&format!("@media (min-width:{key}){{"));
        out.push_str(nl);
        write_block(&mut out, bucket, opts, 1);
        out.push('}');
        out.push_str(nl);
    }

    out
}

fn write_block(out: &mut String, rules: &[&Rule], opts: &EmitOptions, depth: usize) {
    let indent = if opts.minify { "" } else { &"  ".repeat(depth) };
    let nl = if opts.minify { "" } else { "\n" };

    struct Item {
        selectors: Vec<String>,
        decls: String,
        srcs: Vec<String>,
    }
    let mut groups: IndexMap<String, Item> = IndexMap::new();

    for r in rules {
        let decls = render_decls(&r.decls, opts);
        let key = if opts.dedup { decls.clone() } else { format!("{}\u{1}{}", r.selector(), decls) };
        let entry = groups.entry(key).or_insert_with(|| Item {
            selectors: Vec::new(),
            decls: decls.clone(),
            srcs: Vec::new(),
        });
        entry.selectors.push(r.selector());
        entry.srcs.push(r.src.clone());
    }

    for item in groups.values() {
        if opts.source_comments && !opts.minify {
            out.push_str(indent);
            out.push_str(&format!("/* {} */\n", item.srcs.join(", ")));
        }
        out.push_str(indent);
        let sep = if opts.minify { "," } else { ",\n" };
        out.push_str(&item.selectors.join(sep));
        if opts.minify {
            out.push('{');
        } else {
            out.push_str(" {\n");
        }
        out.push_str(&item.decls);
        if opts.minify {
            out.push('}');
        } else {
            out.push_str(indent);
            out.push_str("}\n");
        }
        out.push_str(if opts.minify { "" } else { nl });
    }
}

fn render_decls(decls: &[crate::generate::Decl], opts: &EmitOptions) -> String {
    if opts.minify {
        decls
            .iter()
            .map(|d| format!("{}:{}", d.prop, d.value))
            .collect::<Vec<_>>()
            .join(";")
    } else {
        let mut s = String::new();
        for d in decls {
            s.push_str("    ");
            s.push_str(&d.prop);
            s.push_str(": ");
            s.push_str(&d.value);
            s.push_str(";\n");
        }
        s
    }
}

pub enum TokenFormat {
    Json,
    Js,
    CssVars,
}

const EXPORT_GROUPS: &[(&str, Group)] = &[
    ("colors", Group::Colors),
    ("spacing", Group::Spacing),
    ("sizes", Group::Sizes),
    ("fonts", Group::Fonts),
    ("text", Group::Text),
    ("radius", Group::Radius),
    ("shadows", Group::Shadows),
];

pub fn emit_tokens(theme: &ResolvedTheme, format: TokenFormat) -> String {
    match format {
        TokenFormat::Json => tokens_json(theme),
        TokenFormat::Js => format!("export default {};\n", tokens_json(theme)),
        TokenFormat::CssVars => tokens_css_vars(theme),
    }
}

fn tokens_json(theme: &ResolvedTheme) -> String {
    let mut out = String::from("{\n");
    let mut groups: Vec<String> = Vec::new();
    for (name, g) in EXPORT_GROUPS {
        let map = theme.group(*g);
        let mut entries: Vec<String> = Vec::new();
        for (k, v) in map {
            entries.push(format!("    {}: {}", json_str(k), json_str(v)));
        }
        groups.push(format!("  {}: {{\n{}\n  }}", json_str(name), entries.join(",\n")));
    }
    let mut bps: Vec<String> = Vec::new();
    for (k, v) in &theme.breakpoints {
        bps.push(format!("    {}: {}", json_str(k), json_str(v)));
    }
    groups.push(format!("  {}: {{\n{}\n  }}", json_str("breakpoints"), bps.join(",\n")));

    out.push_str(&groups.join(",\n"));
    out.push_str("\n}\n");
    out
}

fn tokens_css_vars(theme: &ResolvedTheme) -> String {
    let mut out = String::from(":root {\n");
    for (name, g) in EXPORT_GROUPS {
        let prefix = match *name {
            "colors" => "color",
            "spacing" => "space",
            "sizes" => "size",
            "fonts" => "font",
            "text" => "text",
            "radius" => "radius",
            "shadows" => "shadow",
            other => other,
        };
        for (k, v) in theme.group(*g) {
            out.push_str(&format!("  --{prefix}-{k}: {v};\n"));
        }
    }
    for (k, v) in &theme.breakpoints {
        out.push_str(&format!("  --bp-{k}: {v};\n"));
    }
    out.push_str("}\n");
    out
}

fn json_str(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}
